### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by halquabeh** [arnab-api/romba#5]
Thanks for the efforts, appreciate it,
Im facing problem with loading the pretrained model 
"No module named 'mamba.mamba_ssm.models'"
thanks 
Hilal

**Comment by arnab-api** [comment]
Hi,

I should fix the issue with recursive dependency with another git repo. Thanks for bringing that to my attention.

For now you can get a minimal implementation of Mamba with the following command. Make sure you are at the project root.
```
git clone https://github.com/johnma2006/mamba-minimal.git mamba_minimal
```

**Comment by arnab-api** [comment]
Assuming the issue has been resolved. Closing
